spring:
  application:
    name: productos-service
  config:
    import: "optional:configserver:http://localhost:8888"

spring.cloud.config.label: master   # <- que coincida con el server

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"